ARG HUGO_VERSION=0.68.3

FROM acend/hugo:${HUGO_VERSION} AS builder

EXPOSE 8080

# add git - required for Hugo GitInfo
RUN apk add git && rm -rf /var/cache/apk/*

RUN mkdir -p /opt/app/src/static && \
    chmod -R og+rwx /opt/app

WORKDIR /opt/app/src

COPY . /opt/app/src

RUN hugo --theme ${HUGO_THEME:-dot} --minify

FROM alpine
RUN apk --no-cache add thttpd 
COPY --from=builder /opt/app/src/public /var/www
ENTRYPOINT ["/usr/sbin/thttpd", "-p", "8080", "-D", "-r", "-d", "/var/www/"]
